SELECT NAME, OPEN_MODE FROM V$PDBS;
ALTER SESSION SET CONTAINER = CDB$ROOT;

ALTER PLUGGABLE DATABASE PDBORCL CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE PDBORCL INCLUDING DATAFILES;

CREATE PLUGGABLE DATABASE PDBORCL
ADMIN USER pdbadmin IDENTIFIED BY Password123
ROLES = (DBA)
FILE_NAME_CONVERT = ('/opt/oracle/oradata/XE/pdbseed/', '/opt/oracle/oradata/XE/PDBORCL/');

ALTER PLUGGABLE DATABASE PDBORCL OPEN;

ALTER SESSION SET CONTAINER = PDBORCL;

SELECT NAME FROM V$CONTAINERS WHERE CON_ID = SYS_CONTEXT('USERENV','CON_ID');

CREATE TABLESPACE USERS 
DATAFILE '/opt/oracle/oradata/XE/PDBORCL/users01.dbf' 
SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;

---

CREATE USER LPV IDENTIFIED BY Password123
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CONNECT, RESOURCE TO LPV;
GRANT CREATE SESSION TO LPV;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE SEQUENCE, CREATE SYNONYM, CREATE DATABASE LINK TO LPV;
GRANT RESTRICTED SESSION TO LPV;

SELECT USERNAME, ACCOUNT_STATUS FROM DBA_USERS WHERE USERNAME = 'LPV';

---

DROP DATABASE LINK NAN_db;

CREATE DATABASE LINK NAN_db 
   CONNECT TO "NAN"
   IDENTIFIED BY "12345"
   USING '26.255.29.148:1521/PDBORCL';
   
SELECT * FROM CITY@NAN_db;

---

DROP DATABASE LINK VAV_db;

CREATE DATABASE LINK VAV_db 
   CONNECT TO VAV
   IDENTIFIED BY "Password123"
   USING '26.69.212.139:1521/PDBORCL';
   
SELECT * FROM employees@VAV_db;





ALTER SESSION SET CONTAINER = CDB$ROOT;
